<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [23]:
#импорт всех нужных библиотек
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error

In [24]:
#загрузка данных
try:
    df = pd.read_csv('/datasets/insurance.csv')
except FileNotFoundError:
    print("File not found.")
df.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Пропусков нет, целевым признаком является стоолбец "Страховые выплаты". Признаки - это пол, возраст и зарплата застрахованного, количество членов его семьи.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответьте на вопрос и обоснуйте решение**

 Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)
 1. Изменится. Приведите примеры матриц.
 2. Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.

Пусть $X_1 = XA$, и существует обратная к $A$ матрица. Тогда $w_1 = (X_1^T X_1)^{-1}X_1^T y$.

Теперь подставляем выражения для матрицы $X_1$: $w_1 = ((XA)^T XA)^{-1}(XA)^T y = (A^T X^T X A)^{-1}A^T X^T y = A^{-1} (X^T X)^{-1} (A^T)^{-1} A^T X^T y $

$(A^T)^{-1} A^T = I$ $\rightarrow$ $w_1 = A^{-1} (X^T X)^{-1} X^T y = A^{-1} (X^T X)^{-1} X^T y = A^{-1} w$.

Следовательно, вектор весов будет равен $w_1 = A^{-1} w$. Посмотрим, как изменятся предсказания. $a = X_1 w_1 = (XA) A^{-1} w = X w$.

То есть вектор предсказаний не изменяется, следовательно, качество линейной регрессии не изменится.

**Ответ:** качество линейной регрессии не изменится

**Обоснование:** изменятся веса линейной регрессии, но предсказания останутся неизменными

## Алгоритм преобразования

**Алгоритм**

Чтобы защитить данные, нужно будет умножить на рандомную квадратную матрицу. Её размеры определяются количеством столбцов матрицы признаков. В нашем случае будет матрица $4 * 4$. Также нужно проверить, что существует обратная.

In [26]:
#создадим матрицу из случайных чисел
A = np.random.randint(10, size=(4,4))
print(A)

[[0 6 6 9]
 [6 8 3 4]
 [3 4 7 4]
 [6 8 9 3]]
[[0 6 6 9]
 [6 8 3 4]
 [3 4 7 4]
 [6 8 9 3]]


In [27]:
#проверяем на обратимость
B = np.linalg.inv(A)
print(B)

[[-0.22222222  0.23809524  0.5047619  -0.32380952]
 [ 0.16666667 -0.07142857 -0.57142857  0.35714286]
 [ 0.         -0.14285714  0.05714286  0.11428571]
 [ 0.          0.14285714  0.34285714 -0.31428571]]
[[-0.22222222  0.23809524  0.5047619  -0.32380952]
 [ 0.16666667 -0.07142857 -0.57142857  0.35714286]
 [ 0.         -0.14285714  0.05714286  0.11428571]
 [ 0.          0.14285714  0.34285714 -0.31428571]]


In [28]:
#разобьём данные на признаки и target
features = df.drop('Страховые выплаты', axis=1)
target = df['Страховые выплаты']

In [29]:
#масштабируем данные
scaler = StandardScaler()
scaler.fit(features)
features_sc = scaler.transform(features)

$$
w = (X^T X)^{-1} X^T y
$$

In [30]:
w = np.linalg.inv(features_sc.T @ features_sc) @ features_sc.T @ target

$$
a = Xw
$$

In [31]:
a = features_sc @ w

$$
w_1 = (X_1^T X_1)^{-1}X_1^T y = (A^T X^T X A)^{-1}A^T X^T y
$$

In [32]:
w1 = np.linalg.inv(A.T @ features_sc.T @ features_sc @ A) @ A.T @ features_sc.T @ target

$$ a_1 = X_1 w_1 $$

In [33]:
a1 = features_sc @ A @ w1

In [34]:
print(sum(a - a1))

-4.5674218801614735e-14
-4.5674218801614735e-14


Рзаницы между предсказаниями линейной регрессии до преобразования признаков и после практически нулевая. Поэтому качество модели, действительно, не ухудшается.

**Обоснование**

Полученная разница между предсказаниями до и после равна -1.2419569767139343e-14.

## Проверка алгоритма

осталось только разбить выборку на тестовую и валидационную. А потом проверить 2 модели.



In [35]:
features_train, features_valid_test, target_train, target_valid_test = train_test_split(
    features, target, test_size=0.4, random_state=12345)

features_valid, features_test, target_valid, target_test = train_test_split(
    features_valid_test, target_valid_test, test_size=0.5, random_state=12345)

In [36]:
model = LinearRegression()
model.fit(features_train, target_train)
predictions_valid = model.predict(features_valid)
r2_valid = r2_score(target_valid, predictions_valid)
print('r2_valid на валидационной выборке до преобразования исходных признаков:', r2_valid)

r2_valid на валидационной выборке до преобразования исходных признаков: 0.4133907776507595
r2_valid на валидационной выборке до преобразования исходных признаков: 0.4133907776507595


In [37]:
predictions_test = model.predict(features_test)
r2_test = r2_score(target_test, predictions_test)
print('r2_score на тестовой выборке до преобразования исходных признаков:', r2_test)

r2_score на тестовой выборке до преобразования исходных признаков: 0.4330822556428551
r2_score на тестовой выборке до преобразования исходных признаков: 0.4330822556428551


На тестовых данных до преобразования модель показала результат лучше, чем на валидационных. Теперь посмотрим на метрику r2 на преоразованных данных.

In [38]:
features_train_A = features_train @ A
features_valid_A = features_valid @ A
features_test_A = features_test @ A
model.fit(features_train_A, target_train)
predictions_valid_A = model.predict(features_valid_A)
r2_valid_A = r2_score(target_valid, predictions_valid_A)
print('r2_score на валидационной выборке после преобразования исходных признаков:', r2_valid_A)

r2_score на валидационной выборке после преобразования исходных признаков: 0.41339077765075793
r2_score на валидационной выборке после преобразования исходных признаков: 0.41339077765075793


In [39]:
predictions_test_A = model.predict(features_test_A)
r2_test_A = r2_score(target_test, predictions_test_A)
print('r2_score на тестовой выборке после преобразования исходных признаков:', r2_test_A)

r2_score на тестовой выборке после преобразования исходных признаков: 0.4330822556428604
r2_score на тестовой выборке после преобразования исходных признаков: 0.4330822556428604


In [40]:
r2_test_A - r2_test

5.329070518200751e-15

5.329070518200751e-15

Опять-таки модель показала лучший результат на тестовой выборке. И различие метрики r2 равно 1.219024881038422e-13. То есть практически 0.

In [41]:
features_A = features @ A

In [42]:
features.head()

Пол  Возраст  Зарплата  Члены семьи
0    1     41.0   49600.0            1
1    0     46.0   38000.0            1
2    0     29.0   21000.0            0
3    0     21.0   41700.0            2
4    1     28.0   26100.0            0

Пол  Возраст  Зарплата  Члены семьи
0    1     41.0   49600.0            1
1    0     46.0   38000.0            1
2    0     29.0   21000.0            0
3    0     21.0   41700.0            2
4    1     28.0   26100.0            0

In [43]:
features_A.head()

0         1         2         3
0  149052.0  198742.0  347338.0  198576.0
1  114282.0  152376.0  266147.0  152187.0
2   63174.0   84232.0  147087.0   84116.0
3  125238.0  166984.0  291981.0  166890.0
4   78468.0  104630.0  182790.0  104521.0

0         1         2         3
0  149052.0  198742.0  347338.0  198576.0
1  114282.0  152376.0  266147.0  152187.0
2   63174.0   84232.0  147087.0   84116.0
3  125238.0  166984.0  291981.0  166890.0
4   78468.0  104630.0  182790.0  104521.0

In [44]:
#восстановление данных
features1 = features_A @ np.linalg.inv(A)
features1.head()

0     1        2             3
0  1.000000e+00  41.0  49600.0  1.000000e+00
1 -1.409761e-12  46.0  38000.0  1.000000e+00
2 -1.729727e-13  29.0  21000.0 -2.480682e-12
3  8.804069e-13  21.0  41700.0  2.000000e+00
4  1.000000e+00  28.0  26100.0 -5.989209e-12

0     1        2             3
0  1.000000e+00  41.0  49600.0  1.000000e+00
1 -1.409761e-12  46.0  38000.0  1.000000e+00
2 -1.729727e-13  29.0  21000.0 -2.480682e-12
3  8.804069e-13  21.0  41700.0  2.000000e+00
4  1.000000e+00  28.0  26100.0 -5.989209e-12

Исходные данные можно восстановить, если домножить преобразованную матрицу признаков справа на матрицу $A^{-1}$.

**Вывод**

С помощью преобразования исходных признаков, мы можем защитить данные. Как показали исследования на конечный результат это никак не повлияло, метрика r2 практически не отличается для этих двух случаев.